uknews/newsapp/urls.py
from django.urls import path, include
from newsapp import views

app_name = "newsapp"

urlpatterns = [
    path('', views.mainpage, name='mainpage'),
    path('auth_login/', views.auth_login, name='auth_login'),
    path('create_account/', views.create_account, name='create_account'),
    path('auth_logout/', views.auth_logout, name='auth_logout'),
    path('get_distinct_categories/', views.get_distinct_categories, name='get_distinct_categories'),
    path('browse_category/<slug:category_value>/', views.browse_category, name='browse_category'),
    path('profile/', views.profile, name='profile'),
    path('update_categories/', views.update_categories, name='update_categories'),
    path('get_favourite_categories/', views.get_favourite_categories, name='get_favourite_categories'),
    path('like_article/', views.like_article, name='like_article'),
    path('article_page/<int:article_id>/', views.article_page, name='article_page'),
    path('create_comment/', views.create_comment, name='create_comment'),
    path('delete_comment/', views.delete_comment, name='delete_comment'),
    path('edit_comment/', views.edit_comment, name='edit_comment'),
]

uknews/uknews/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("newsapp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uknews/newsapp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    favourite_category = models.CharField(max_length=999,blank=True, null=True)
    picture = models.ImageField(upload_to='picture', blank=True, null=True)
    date_of_birth = models.DateField()

class Article(models.Model):
	article_name = models.CharField(max_length=999)
	article_category = models.CharField(max_length=999)
	article_description = models.CharField(max_length=999)
	article_likes = models.ManyToManyField(User, related_name='article_likes')
	article_created_time = models.DateTimeField(default=datetime.now)

class Comment(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="article")
	comment_text = models.CharField(max_length=999)
	comment_created_time = models.DateTimeField(default=datetime.now)

uknews/newsapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .models import Profile, Article, Comment
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.core import serializers
from django.conf import settings
import json
import os

import random

from django.core.mail import send_mail


def random_article():
    category = ["Sport", "Finance", "Entertainment", "World"]
    for i in range(10):
        print(i)
        chosen_category = random.choice(category)
        article_name = chosen_category + " " + str(i)
        article_description = "This is the desription for article {}".format(
            chosen_category)
        Article.objects.create(
            article_name=article_name,
            article_category=chosen_category,
            article_description=article_description
        )
    return


def mainpage(request):
    return render(request, "newsapp/mainpage.html", {})


def edit_comment(request):
    if not request.user.is_authenticated:
        context = {
            "message": "You need to be logged in to post a comment on any article. "}
        return HttpResponse(json.dumps(context), content_type="application/json")

    new_comment = request.GET.get('new_comment', None)
    comment_id = request.GET.get('comment_id', None)
    print("comment_id", comment_id)

    comment = Comment.objects.get(id=int(comment_id))
    comment.comment_text = new_comment
    comment.save(update_fields=['comment_text'])

    context = {"comment": serializers.serialize("json", [comment, ])}
    return HttpResponse(json.dumps(context), content_type="application/json")


def create_comment(request):
    if not request.user.is_authenticated:
        context = {
            "message": "You need to be logged in to post a comment on any article. "}
        return HttpResponse(json.dumps(context), content_type="application/json")

    comment_text = request.GET.get('comment', None)
    article_id = request.GET.get('article_id', None)
    user = User.objects.get(id=int(request.user.pk))
    article = Article.objects.get(id=int(article_id))

    comment = Comment.objects.create(
        user=user,
        article=article,
        comment_text=comment_text
    )
    context = {"comment": serializers.serialize(
        "json", [comment, ]), "user": serializers.serialize("json", [user, ])}
    return HttpResponse(json.dumps(context), content_type="application/json")


def article_page(request, article_id):
    article = Article.objects.get(id=article_id)
    all_comments = Comment.objects.filter(
        article=article).order_by('-comment_created_time')
    context = {"article": article,
               "all_comments": all_comments}
    return render(request, "newsapp/articlepage.html", context)


def delete_comment(request):
    comment_id = request.GET.get('comment_id', None)

    Comment.objects.filter(id=int(comment_id)).delete()
    context = {"status": "OK"}
    return HttpResponse(json.dumps(context), content_type="§application/json")


def get_distinct_categories(request):
    # Display the categories in the nav bar for all the users.
    # So the users can browse thorugh each article by category.
    unique_categories = list(Article.objects.all().values_list(
        'article_category', flat=True).distinct())
    unique_categories.sort()
    response = {"unique_categories": unique_categories}
    return HttpResponse(json.dumps(response), content_type="application/json")


def get_favourite_categories(request):
    profile = Profile.objects.get(user=request.user.pk)
    favourite_categories = profile.favourite_category.split(
        ",") if profile.favourite_category else []
    favourite_categories.sort()
    response = {"favourite_categories": favourite_categories}
    return HttpResponse(json.dumps(response), content_type="application/json")


def auth_login(request):
    if request.method == "POST" and "login_account" in request.POST:
        email_address = request.POST["email_address"]
        password = request.POST["password"]

        if not request.POST.get('remember_me', None):
            # User checked remember me option.
            request.session.set_expiry(0)

        user = authenticate(username=email_address, password=password)
        if user:
            login(request, user)
            return redirect('newsapp:mainpage')
        else:
            context = {
                "message": "Oops! There's an issue with your credentials!"}
            return render(request, "newsapp/login.html", context)

    return render(request, "newsapp/login.html", {})


def auth_logout(request):
    logout(request)
    return redirect('newsapp:auth_login')


def browse_category(request, category_value):
    print(category_value)
    articles = Article.objects.filter(
        article_category__icontains=category_value)
    print(articles)
    return render(request, "newsapp/mainpage.html", {"articles": articles})


def like_article(request):
    if not request.user.is_authenticated:
        response = {"message": "Please login to like this article."}
        return HttpResponse(json.dumps(response), content_type="application/json")

    user = User.objects.get(id=int(request.user.pk))
    article_id = request.GET.get('article_id', None)
    article = Article.objects.get(id=int(article_id))
    liked = Article.objects.filter(article_likes__id=user.pk)

    if(article not in liked):
        user.article_likes.add(article)
    else:
        user.article_likes.remove(article)

    response = {"article": serializers.serialize("json", [article, ]), }
    return HttpResponse(json.dumps(response), content_type="application/json")


def create_account(request):
    if request.method == "POST" and "create_account" in request.POST:
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        email_address = request.POST["email_address"]
        password = request.POST["password"]
        date_of_birth = request.POST["date_of_birth"]

        # Creating User model and a profile for this user.

        # Checking if an account already created with the email.

        if User.objects.filter(username=email_address).exists():
            context = {"message": "Error creating account. Email already used."}
            return render(request, "newsapp/registration.html", context)

        new_user = User.objects.create_user(
            username=email_address,
            email=email_address,
            password=password,
            first_name=first_name,
            last_name=last_name,
        )

        new_profile = Profile.objects.create(
            user=new_user, date_of_birth=date_of_birth)

        # Sending a welcome email to the user.
        send_register_email(email_address, first_name)

    context = {"message": "Account created successfully!"}
    return render(request, "newsapp/registration.html", context)

    return render(request, "newsapp/registration.html", {})


def profile(request):
    if not request.user.is_authenticated:
        return redirect('newsapp:auth_login')

    profile = Profile.objects.get(user=request.user.pk)

    print(profile.picture.name)
    print()

    if request.method == "POST" and "delete_picture" in request.POST:
        if profile.picture:
            previous_image = os.path.join(
                settings.MEDIA_ROOT, profile.picture.name)
            if os.path.exists(previous_image):
                os.remove(previous_image)

    if request.method == "POST" and "new_picture" in request.POST:
        if "my-file-selector" in request.FILES:
            if profile.picture:
                previous_image = os.path.join(
                    settings.MEDIA_ROOT, profile.picture.name)
                if os.path.exists(previous_image):
                    os.remove(previous_image)

            new_picture = request.FILES["my-file-selector"]
            profile.picture = new_picture
            profile.save(update_fields=['picture'])

    unique_categories = Article.objects.all().values_list(
        'article_category', flat=True).distinct()
    context = {"profile": profile, "unique_categories": unique_categories}
    return render(request, "newsapp/profile.html", context)


def update_categories(request):
    new_categories = request.GET.getlist('new_categories[]', None)
    new_categories = ','.join(new_categories)
    Profile.objects.filter(user=request.user.pk).update(
        favourite_category=new_categories)
    response = {"message": "Your category has been updated successfully!"}
    return HttpResponse(json.dumps(response), content_type="application/json")


def send_register_email(emailTo, name):
    print("SENDING EMAIL TO: " + emailTo)

    message = 'Dear ' + name + ' ,'\
        '\n\nWelcome to the greatest UK News App. You can find all the latest updates right here!\n\nRegards,\nHuzefa & Jeevan'

    send_mail('Thank you for registering to UK News App!', message,
              settings.EMAIL_HOST_USER, [emailTo], fail_silently=False,)

uknews/newsapp/templates/newsapp/articlepage.html
{% extends "newsapp/base.html" %} {% load static %} {% block content %}
<style type="text/css">
    .comment-wrapper .panel-body {
        max-height: 650px;
        overflow: auto;
    }
    
    .comment-wrapper .media-list .media img {
        width: 64px;
        height: 64px;
        border: 2px solid #e5e7e8;
    }
    
    .comment-wrapper .media-list .media {
        border-bottom: 1px dashed #efefef;
        margin-bottom: 25px;
    }
</style>
<div class="container">
    <div class="jumbotron">
        <h2 style="text-align: center;">{{ article.article_name }}</h2>
    </div>
    <div id="article-description">
        <p>{{ article.article_description }}</p>
    </div>
    <br><br>
    <div id="article-comments">
        <div class="row bootstrap snippets bootdeys">
            <div class="col-md-8 col-sm-12">
                <div class="comment-wrapper">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h4>Comment panel</h4>
                        </div>
                        <div class="panel-body">
                            <textarea class="form-control" placeholder="write a comment..." rows="3" id="comment-box"></textarea>
                            <br>
                            <button type="button" class="btn btn-info pull-right" onclick="create_comment()">Post</button>
                            <div class="clearfix"></div>
                            <hr>
                            <ul class="media-list" id="list-of-article-comments">
                                <!--  -->
                                <!--  -->
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Edit your comment below.</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Message:</label>
                        <textarea class="form-control" id="message-text-to-edit" rows="5"></textarea>
                        <input type="text" id="comment_id_modal">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="update-comment-button">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function onloadcomments() {
		alert();
        {%
            if all_comments %
        } { %
            for comment in all_comments %
        }


        if ("{{comment.user.email}}" == "{{ user.get_username }}") {
            $('#list-of-article-comments').append(`<li id="comment_id_{{comment.id}}" class="media"> <div class="media-body"> <span class="text-muted pull-right"> <small class="text-muted">{{comment.comment_created_time}}</small> </span> <strong class="text-success">By {{comment.user.first_name}}</strong> <p id="comment_text_{{comment.id}}">{{comment.comment_text}}</p><button type='button' class='btn btn-danger' onclick='deletecomment({{comment.id}})'><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg"> <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/> <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/></svg></button>&nbsp;&nbsp;&nbsp;&nbsp;<button type='button' class='btn btn-info' onclick='editcomment({{comment.id}})' data-toggle="modal" data-target="#exampleModalCenter"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/></svg></button> </div></li>`);
        } else {
            $('#list-of-article-comments').append(`<li id="comment_id_{{comment.id}}" class="media"> <div class="media-body"> <span class="text-muted pull-right"> <small class="text-muted">{{comment.comment_created_time}}</small> </span> <strong class="text-success">By{{comment.user.first_name}}</strong> <p id="comment_text_{{comment.id}}">{{comment.comment_text}}</p></div></li>`);
        }
        //add reply button
        $('#list-of-article-comments').append



        { % endfor %
        } { % endif %
        }

    }
    onloadcomments();

    function deletecomment(comment_id) {
        $.ajax({
            url: '{% url "newsapp:delete_comment" %}',
            data: {
                'comment_id': comment_id
            },
            dataType: 'json',
            success: function(response) {
                if (response.status == "OK") {
                    $("#comment_id_" + comment_id).remove();
                }
            }
        });
    }

    document.getElementById("update-comment-button").addEventListener("click", function() {
        $('#exampleModalCenter').modal('hide');
        var new_comment = $('textarea#message-text-to-edit').val();
        var comment_id = $('input#comment_id_modal').val();

        $.ajax({
            url: '{% url "newsapp:edit_comment" %}',
            dataType: 'json',
            data: {
                'new_comment': new_comment,
                'comment_id': comment_id,
            },
            success: function(response) {
                if (response.hasOwnProperty('message')) {
                    alert(response.message);
                    return;
                }
                var comment = eval(response.comment)[0].fields.comment_text;
                $('p#comment_text_' + comment_id).text(comment);
            }
        });

    })

    function editcomment(comment_id) {
        comment_text = $('p#comment_text_' + comment_id).text();
        $("textarea#message-text-to-edit").val(comment_text);
        $('#comment_id_modal').val(comment_id);
    }


    function create_comment() {
        var comment = $('textarea#comment-box').val();

        if (comment.trim().length < 1) {
            alert("Enter something!")
            return;
        } else {
            $('textarea#comment-box').val('');
        }
        $.ajax({
            url: '{% url "newsapp:create_comment" %}',
            dataType: 'json',
            data: {
                'comment': comment,
                "article_id": "{{ article.id }}",
            },
            success: function(response) {
                if (response.hasOwnProperty('message')) {
                    alert(response.message);
                    return;
                }

                var user = eval(response.user)[0].fields;
                var comment = eval(response.comment)[0].fields;
                var comment_pk = eval(response.comment)[0].pk;

                $(`<li id="comment_id_` + comment_pk + `" class="media"> <div class="media-body"> <span class="text-muted pull-right"> <small class="text-muted">` + comment.comment_created_time + `</small> </span> <strong class="text-success">By ` + user.first_name + `</strong> <p id="comment_text_` + comment_pk + `">` + comment.comment_text + `</p><button type='button' class='btn btn-danger' onclick='deletecomment(` + comment_pk + `)'><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg"> <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/> <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/></svg></button>&nbsp;&nbsp;&nbsp;&nbsp;<button type='button' class='btn btn-info' onclick='editcomment(` + comment_pk + `)' data-toggle="modal" data-target="#exampleModalCenter"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/></svg></button> </div></li>`).prependTo("#list-of-article-comments"); //new comment comes at the top.
            }
        });
    }
</script>
{% endblock %}

uknews/newsapp/templates/newsapp/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>UK News</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet" />
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <!-- <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> Test if error occurs-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>
<style type="text/css">
    body{background-color:#e2e8f0}
</style>
<body>
    <nav class="navbar navbar-expand-lg navbar-light navbar-laravel">
        <div class="container">
            <a class="navbar-brand" href="{% url 'newsapp:mainpage' %}">UK News</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Browse Articles
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" id="categories-for-all-user">
                        </div>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'newsapp:profile' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'newsapp:auth_logout' %}">Logout</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">My Favourite Article
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" id="favourite-categories">
                        </div>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'newsapp:auth_login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'newsapp:create_account' %}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>
<script type="text/javascript">
    window.onload = function() {
        // Get distinct article categories and display the categories in the nav bar
        $.ajax({
          url: '{% url "newsapp:get_distinct_categories" %}',
          dataType: 'json',
          success: function (response) {
            for (var i = 0; i < response.unique_categories.length; i++) {
                var category_url = '<a class="dropdown-item" href="/browse_category/'+response.unique_categories[i]+'">'+response.unique_categories[i]+'</a>';
                $( "#categories-for-all-user" ).append( category_url );
            }
          }
        });

        // TODO: Making another ajax request to retrive user's favourite categories.

        {% if user.is_authenticated %}
            $.ajax({
              url: '{% url "newsapp:get_favourite_categories" %}',
              dataType: 'json',
              success: function (response) {
                for (var i = 0; i < response.favourite_categories.length; i++) {
                var category_url = '<a class="dropdown-item" href="/browse_category/'+response.favourite_categories[i]+'">'+response.favourite_categories[i]+'</a>';
                $( "#favourite-categories" ).append( category_url );
            }
              }
            });
        {% endif %}
        
    }
</script>
</html>

uknews/newsapp/templates/newsapp/login.html
{% extends "newsapp/base.html" %}
{% load static %}
{% block content %}
<style type="text/css">
  body{margin:0;font-size:.9rem;font-weight:400;line-height:1.6;color:#212529;text-align:left;background-color:#f5f8fa}.navbar-laravel{box-shadow:0 2px 4px rgba(0,0,0,.04)}.login-form,.my-form,.nav-link,.navbar-brand{font-family:Raleway,sans-serif}.my-form{padding-top:1.5rem;padding-bottom:1.5rem}.my-form .row{margin-left:0;margin-right:0}.login-form{padding-top:1.5rem;padding-bottom:1.5rem}.login-form .row{margin-left:0;margin-right:0}
</style>

<div class="container">
   {% if message %}
   <div style="color: black; text-align: center;" class="alert alert-danger" role="alert">{{message}}</div>
   {% endif %}
   <main class="login-form">
      <div class="cotainer">
         <div class="row justify-content-center">
            <div class="col-md-8">
               <div class="card">
                  <div class="card-header">Login</div>
                  <div class="card-body">
                     <form method="post">
                        {% csrf_token %}
                        <input type="text" name="login_account" hidden>
                        <div class="form-group row">
                           <label for="email_address" class="col-md-4 col-form-label text-md-right">E-Mail</label>
                           <div class="col-md-6">
                              <input type="text" id="email_address" class="form-control" name="email_address" required autofocus>
                           </div>
                        </div>
                        <div class="form-group row">
                           <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>
                           <div class="col-md-6">
                              <input type="password" id="password" class="form-control" name="password" required>
                           </div>
                        </div>
                        <div class="form-group row">
                           <div class="col-md-6 offset-md-4">
                              <div class="checkbox">
                                 <label>
                                 <input type="checkbox" name="remember_me"> Remember Me
                                 </label>
                              </div>
                           </div>
                        </div>
                        <div class="col-md-6 offset-md-4">
                           <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                  </div>
                  </form>
               </div>
            </div>
          </div>
        </div>
      </div>
    </main>
</div>
{% endblock %}